package main

import (
	"bytes"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"barney.ci/go-json5"
)

// Config is the validated configuration for webrtc-forward.
type Config struct {
	Services     map[string]string  // service name → host:port
	Coordinators []string           // WebSocket URLs of coordinators to register with
	PrivKey      ed25519.PrivateKey // node identity key
}

var allowedTopLevel = []string{"services", "coordinators", "key"}

// LoadConfig reads and strictly validates a JSON5 config file.
func LoadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("cannot read config file %q: %w", path, err)
	}

	// Translate JSON5 → JSON, then parse to a raw map for strict key validation.
	jsonBytes, err := io.ReadAll(json5.NewReader(bytes.NewReader(data)))
	if err != nil {
		return nil, fmt.Errorf("config parse error: %w", err)
	}
	var raw map[string]interface{}
	if err := json.Unmarshal(jsonBytes, &raw); err != nil {
		return nil, fmt.Errorf("config parse error: %w", err)
	}

	// Reject unknown top-level keys.
	if err := rejectUnknown("config", raw, allowedTopLevel); err != nil {
		return nil, err
	}

	cfg := &Config{Services: make(map[string]string)}

	// ── services ──────────────────────────────────────────────────────────────
	if svcVal, ok := raw["services"]; ok {
		svcMap, ok := svcVal.(map[string]interface{})
		if !ok {
			return nil, fmt.Errorf(`config: "services" must be an object, got %s`, typeName(svcVal))
		}
		for name, val := range svcMap {
			addr, ok := val.(string)
			if !ok {
				return nil, fmt.Errorf(`config: services[%q] must be a string, got %s`, name, typeName(val))
			}
			if addr == "" {
				return nil, fmt.Errorf(`config: services[%q] must not be empty`, name)
			}
			cfg.Services[name] = addr
		}
	}

	// ── coordinators ──────────────────────────────────────────────────────────
	if cVal, ok := raw["coordinators"]; ok {
		cArr, ok := cVal.([]interface{})
		if !ok {
			return nil, fmt.Errorf(`config: "coordinators" must be an array, got %s`, typeName(cVal))
		}
		for i, v := range cArr {
			s, ok := v.(string)
			if !ok {
				return nil, fmt.Errorf(`config: coordinators[%d] must be a string, got %s`, i, typeName(v))
			}
			if s == "" {
				return nil, fmt.Errorf(`config: coordinators[%d] must not be empty`, i)
			}
			cfg.Coordinators = append(cfg.Coordinators, s)
		}
	}
	if len(cfg.Coordinators) == 0 {
		return nil, fmt.Errorf(`config: "coordinators" is required and must have at least one entry`)
	}

	// ── key ───────────────────────────────────────────────────────────────────
	kVal, ok := raw["key"]
	if !ok {
		return nil, fmt.Errorf(`config: "key" is required (run init to generate one)`)
	}
	kStr, ok := kVal.(string)
	if !ok {
		return nil, fmt.Errorf(`config: "key" must be a string, got %s`, typeName(kVal))
	}
	privBytes, err := base64.StdEncoding.DecodeString(kStr)
	if err != nil {
		return nil, fmt.Errorf(`config: "key" is not valid base64: %w`, err)
	}
	if len(privBytes) != ed25519.PrivateKeySize {
		return nil, fmt.Errorf(`config: "key" must be %d bytes (got %d)`, ed25519.PrivateKeySize, len(privBytes))
	}
	cfg.PrivKey = ed25519.PrivateKey(privBytes)

	return cfg, nil
}

// rejectUnknown returns an error if raw contains any key not in allowed.
func rejectUnknown(section string, raw map[string]interface{}, allowed []string) error {
	set := make(map[string]bool, len(allowed))
	for _, k := range allowed {
		set[k] = true
	}
	var unknown []string
	for k := range raw {
		if !set[k] {
			unknown = append(unknown, fmt.Sprintf("%q", k))
		}
	}
	if len(unknown) > 0 {
		quoted := make([]string, len(allowed))
		for i, k := range allowed {
			quoted[i] = fmt.Sprintf("%q", k)
		}
		return fmt.Errorf(`config: unknown field(s) in %s: %s (allowed: %s)`,
			section, strings.Join(unknown, ", "), strings.Join(quoted, ", "))
	}
	return nil
}

// typeName returns a human-readable name for the dynamic type of v.
func typeName(v interface{}) string {
	switch v.(type) {
	case bool:
		return "boolean"
	case float64:
		return "number"
	case string:
		return "string"
	case []interface{}:
		return "array"
	case map[string]interface{}:
		return "object"
	case nil:
		return "null"
	default:
		return fmt.Sprintf("%T", v)
	}
}

// GenerateSampleConfig generates a config file with a fresh ed25519 key embedded.
func GenerateSampleConfig(privKey ed25519.PrivateKey) string {
	keyB64 := base64.StdEncoding.EncodeToString(privKey)
	return `{
  // Map of service names to TCP host:port targets.
  services: {
    // example: "127.0.0.1:7777",
  },

  // Coordinator WebSocket URLs to register with.
  coordinators: ["wss://example.com/ws"],

  // Node identity key (ed25519 private key, base64). Generated by init.
  key: "` + keyB64 + `",
}
`
}
